package ai.docling.serve.api.convert.response;

import java.net.URI;
import java.time.Instant;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a reference to a single output artifact returned as a presigned URL.
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * fields are omitted from JSON output.</p>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = ArtifactRef.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class ArtifactRef {

  /**
   * Export format of the artifact.
   *
   * @param artifactType the artifact type
   * @return the artifact type
   */
  @JsonProperty("artifact_type")
  private ArtifactType artifactType;

  /**
   * MIME type of the artifact content.
   *
   * @param mimeType the MIME type
   * @return the MIME type
   */
  @JsonProperty("mime_type")
  private String mimeType;

  /**
   * Presigned URL used to download the artifact.
   *
   * @param uri the presigned URL
   * @return the presigned URL
   */
  @JsonProperty("uri")
  private URI uri;

  /**
   * Instant at which the presigned URL signature stops being valid.
   *
   * @param urlExpiresAt the expiry timestamp
   * @return the expiry timestamp
   */
  @JsonProperty("url_expires_at")
  private Instant urlExpiresAt;

  /**
   * Builder for creating {@link ArtifactRef} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   *
   * <p>Builder methods:
   * <ul>
   *   <li>{@code artifactType(ArtifactType)} - Set the artifact type</li>
   *   <li>{@code mimeType(String)} - Set the MIME type</li>
   *   <li>{@code uri(URI)} - Set the presigned URL</li>
   *   <li>{@code urlExpiresAt(Instant)} - Set the expiry timestamp</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
