version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    labels:
      - "version-upgrade"
    commit-message:
      prefix: chore

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - "version-upgrade"
    commit-message:
      prefix: chore
