[versions]
junit-jupiter = "6.0.0"
assertj = "3.27.6"
jackson = "3.0.0"
jspecify = "1.0.0"
testcontainers = "2.0.1"
jackson = "2.20.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
jackson-bom = { group = "tools.jackson", name = "jackson-bom", version.ref = "jackson" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers"}
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }

[bundles]
assertj = ["assertj-core"]
junit-jupiter = ["junit-jupiter"]
