name: Simple build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 17
          - 21
          - 25
        module:
          - api
          - client
          - docs
          - testing
          - testcontainers
    name: jvm-build-test-${{ matrix.module }}-java${{ matrix.java }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: build-test-${{ matrix.module }}-java${{ matrix.java }}
        run: |
          ./gradlew --no-daemon -Pjava.version=${{ matrix.java }} 
            :docling-${{ matrix.module }}:clean :docling-${{ matrix.module }}:build
